-- Migration: Populate content_type table with report types
-- Purpose: Define the types of reports that can be generated by the LLM
-- Date: 2024
-- Description: This migration adds the predefined content types for final reports

-- Insert content types for different report formats
-- The LLM will decide which type to use based on content analysis

INSERT INTO content_type (name) VALUES 
('short_news'),      -- Short news article (brief summary)
('medium_news'),     -- Medium-length news article (moderate detail)
('long_news'),       -- Long news article (comprehensive coverage)
('explanation'),     -- Explanatory article (educational/informative)
('analysis')         -- Analytical article (in-depth analysis)
ON CONFLICT (name) DO NOTHING;

-- Add comments for documentation
COMMENT ON TABLE content_type IS 'Defines the types of reports that can be generated from clustered news';
